SELECT DISTINCT ON (s.id_soggetto) s.id,
    s.id_soggetto,
    s.codice_fiscale,
    s.cciaa,
    s.nrea,
    s.denominazione,
    s.toponimo_cd,
    s.indirizzo,
    s.civico,
    s.frazione,
    s.nazione_cd,
    s.cap,
    s.comune_desc,
    s.provincia_cd,
    s.comune_cd,
    s.natura_giuridica_cd,
    s.partita_iva,
    s.ateco07_cd,
    s.sae,
    s.rae,
    s.data_iscrizione,
    s.data_inizio_attivita,
    s.stato_attivita_cd,
    s.tipo_localizzazione_cd,
    s.progressivo_localizzazione,
    s.capitale_deliberato,
    s.capitale_sottoscritto,
    s.capitale_versato,
    s.conferimenti,
    s.prot_data_evaso,
    s.prot_data,
    s.pec,
    s.longitudine_dd,
    s.latitudine_dd,
    s.telefono,
    s.email,
    s.sito_web,
    s.addetti,
    s.fatturato,
    s.startup,
    s.regione,
    s.esclusione,
    s.trend_fatturato,
    s.trend_utile_perdita,
    s.trend_debiti,
    s.trend_redditivita,
    t.descrizione AS toponimo,
    am.codice AS ateco,
    a.descrizione AS ateco_descrizione,
    pr.regione AS regione_esteso,
    pr.provincia AS provincia_esteso,
    ng.descrizione,
    ng.tipo AS tipo_natgiur,
    ame.codice,
    ame.settoreinnolva,
    ame.descrizione_settoreinnolva,
    ame.descrizione_settoreinnolva AS descrizione_settore_innova_short,
    uf.uwebsite,
    uf.utel,
    uf.umail,
    uf.ufacebook,
    uf.uinstagram,
    uf.ulinkedin,
    ufia.info_aggiuntive,
    alcurr.dipendenti::text AS dipendenti_current,
    alcurr.anno::text AS anno_current,
    alcurr.indipendenti::text AS indipendenti_current,
    alcurr.totale::text AS totale_current,
    allast.dipendenti::text AS dipendenti_last,
    allast.anno::text AS anno_last,
    allast.indipendenti::text AS indipendenti_last,
    allast.totale::text AS totale_last,
    blcurr.score_finanziario,
    blcurr.debiti_verso_banche_bt,
    blcurr.risultato_prima_delle_imposte,
    blcurr.patrimonio_netto,
    blcurr.acquisti,
    blcurr.roe,
    blcurr.roi,
    blcurr.ros,
    blcurr.accantonamenti_operativi::text AS accantonamenti_operativi_1,
    bllast.accantonamenti_operativi::text AS accantonamenti_operativi_2,
    blcurr.altre_passivita::text AS altre_passivita_1,
    bllast.altre_passivita::text AS altre_passivita_2,
    blcurr.altre_riserve::text AS altre_riserve_1,
    bllast.altre_riserve::text AS altre_riserve_2,
    blcurr.ammort_immobil_immateriali::text AS ammort_immobil_immateriali_1,
    bllast.ammort_immobil_immateriali::text AS ammort_immobil_immateriali_2,
    blcurr.ammort_immobil_materiali::text AS ammort_immobil_materiali_1,
    bllast.ammort_immobil_materiali::text AS ammort_immobil_materiali_2,
    blcurr.attivo_breve_termine::text AS attivo_breve_termine_1,
    bllast.attivo_breve_termine::text AS attivo_breve_termine_2,
    blcurr.capitale_sociale::text AS capitale_sociale_1,
    bllast.capitale_sociale::text AS capitale_sociale_2,
    blcurr.cash_flow::text AS cash_flow_1,
    bllast.cash_flow::text AS cash_flow_2,
    blcurr.classe_fatturato::text AS classe_fatturato_1,
    bllast.classe_fatturato::text AS classe_fatturato_2,
    blcurr.comparto_cd::text AS comparto_cd_1,
    bllast.comparto_cd::text AS comparto_cd_2,
    blcurr.costo_del_personale::text AS costo_del_personale_1,
    bllast.costo_del_personale::text AS costo_del_personale_2,
    blcurr.crediti_clienti::text AS crediti_clienti_1,
    bllast.crediti_clienti::text AS crediti_clienti_2,
    blcurr.debiti_vs_banche::text AS debiti_vs_banche_1,
    bllast.debiti_vs_banche::text AS debiti_vs_banche_2,
    blcurr.debiti_vs_forn_e_acconti::text AS debiti_vs_forn_e_acconti_1,
    bllast.debiti_vs_forn_e_acconti::text AS debiti_vs_forn_e_acconti_2,
    blcurr.debiti_vs_fornitori::text AS debiti_vs_fornitori_1,
    bllast.debiti_vs_fornitori::text AS debiti_vs_fornitori_2,
    blcurr.ebitda::text AS ebitda_1,
    bllast.ebitda::text AS ebitda_2,
    blcurr.eq_economico::text AS eq_economico_1,
    bllast.eq_economico::text AS eq_economico_2,
    blcurr.eq_efficienza::text AS eq_efficienza_1,
    bllast.eq_efficienza::text AS eq_efficienza_2,
    blcurr.eq_finanziario::text AS eq_finanziario_1,
    bllast.eq_finanziario::text AS eq_finanziario_2,
    blcurr.eq_liquidita::text AS eq_liquidita_1,
    bllast.eq_liquidita::text AS eq_liquidita_2,
    blcurr.eq_patrimoniale::text AS eq_patrimoniale_1,
    bllast.eq_patrimoniale::text AS eq_patrimoniale_2,
    blcurr.fondi_e_altri_debiti_mit::text AS fondi_e_altri_debiti_mit_1,
    bllast.fondi_e_altri_debiti_mit::text AS fondi_e_altri_debiti_mit_2,
    blcurr.immobilizzazioni_finanziarie::text AS immobilizzazioni_finanziarie_1,
    bllast.immobilizzazioni_finanziarie::text AS immobilizzazioni_finanziarie_2,
    blcurr.immobilizzazioni_immateriali::text AS immobilizzazioni_immateriali_1,
    bllast.immobilizzazioni_immateriali::text AS immobilizzazioni_immateriali_2,
    blcurr.immobilizzazioni_materiali::text AS immobilizzazioni_materiali_1,
    bllast.immobilizzazioni_materiali::text AS immobilizzazioni_materiali_2,
    blcurr.imposte_sul_reddito_esercizio::text AS imposte_sul_reddito_esercizio_1,
    bllast.imposte_sul_reddito_esercizio::text AS imposte_sul_reddito_esercizio_2,
    blcurr.liquidita::text AS liquidita_1,
    bllast.liquidita::text AS liquidita_2,
    blcurr.oneri_finanziari::text AS oneri_finanziari_1,
    bllast.oneri_finanziari::text AS oneri_finanziari_2,
    blcurr.passivo_a_breve_termine::text AS passivo_a_breve_termine_1,
    bllast.passivo_a_breve_termine::text AS passivo_a_breve_termine_2,
    blcurr.proventi_finanziari_netti::text AS proventi_finanziari_netti_1,
    bllast.proventi_finanziari_netti::text AS proventi_finanziari_netti_2,
    blcurr.rimanenze::text AS rimanenze_1,
    bllast.rimanenze::text AS rimanenze_2,
    blcurr.risultato_gestione_str::text AS risultato_gestione_str_1,
    bllast.risultato_gestione_str::text AS risultato_gestione_str_2,
    blcurr.risultato_operativo_ebit::text AS risultato_operativo_ebit_1,
    bllast.risultato_operativo_ebit::text AS risultato_operativo_ebit_2,
    blcurr.risultato_operativo_lordo::text AS risultato_operativo_lordo_1,
    bllast.risultato_operativo_lordo::text AS risultato_operativo_lordo_2,
    blcurr.saldo_prov_of::text AS saldo_prov_of_1,
    bllast.saldo_prov_of::text AS saldo_prov_of_2,
    blcurr.saldo_ricavi_oneri_diversi::text AS saldo_ricavi_oneri_diversi_1,
    bllast.saldo_ricavi_oneri_diversi::text AS saldo_ricavi_oneri_diversi_2,
    blcurr.spese_ser_god_beni_terzi::text AS spese_ser_god_beni_terzi_1,
    bllast.spese_ser_god_beni_terzi::text AS spese_ser_god_beni_terzi_2,
    blcurr.sviluppo::text AS sviluppo_1,
    bllast.sviluppo::text AS sviluppo_2,
    blcurr.tipo_bilancio::text AS tipo_bilancio_1,
    bllast.tipo_bilancio::text AS tipo_bilancio_2,
    blcurr.totale_attivo::text AS totale_attivo_1,
    bllast.totale_attivo::text AS totale_attivo_2,
    blcurr.utile_corrente::text AS utile_corrente_1,
    bllast.utile_corrente::text AS utile_corrente_2,
    blcurr.utile_perdita_es_a_riserva::text AS utile_perdita_es_a_riserva_1,
    bllast.utile_perdita_es_a_riserva::text AS utile_perdita_es_a_riserva_2,
    blcurr.valore_aggiunto::text AS valore_aggiunto_1,
    bllast.valore_aggiunto::text AS valore_aggiunto_2,
    blcurr.valore_della_produzione::text AS valore_della_produzione_1,
    bllast.valore_della_produzione::text AS valore_della_produzione_2,
    blcurr.variazione_materie_prime::text AS variazione_materie_prime_1,
    bllast.variazione_materie_prime::text AS variazione_materie_prime_2,
    el1.cd_carica AS cd_carica_1,
    el2.cd_carica AS cd_carica_2,
    el3.cd_carica AS cd_carica_3,
    el4.cd_carica AS cd_carica_4,
    el1.n_anni_esercizio AS n_anni_esercizio_1,
    el2.n_anni_esercizio AS n_anni_esercizio_2,
    el3.n_anni_esercizio AS n_anni_esercizio_3,
    el4.n_anni_esercizio AS n_anni_esercizio_4,
    el1.nascita_comune AS nascita_comune_1,
    el2.nascita_comune AS nascita_comune_2,
    el3.nascita_comune AS nascita_comune_3,
    el4.nascita_comune AS nascita_comune_4,
    el1.nascita_dt AS nascita_dt_1,
    el2.nascita_dt AS nascita_dt_2,
    el3.nascita_dt AS nascita_dt_3,
    el4.nascita_dt AS nascita_dt_4,
    el1.sesso,
    (alcurr.dipendenti::integer - allast.dipendenti::integer) / NULLIF(allast.dipendenti::integer, 0) AS trend_dipendenti,
    s.fatturato / NULLIF(s.addetti, 0)::double precision AS hr
   FROM sedi_latest s
     LEFT JOIN addetti_latest alcurr ON s.id_soggetto::text = alcurr.id_soggetto::text AND alcurr.anno::text = date_part('year'::text, now() - '2 years'::interval)::text
     LEFT JOIN addetti_latest allast ON s.id_soggetto::text = allast.id_soggetto::text AND allast.anno::text = date_part('year'::text, now() - '3 years'::interval)::text
     LEFT JOIN bilanci_latest blcurr ON s.id_soggetto::text = blcurr.id_soggetto::text AND date_part('year'::text, blcurr.data_chiusura_bilancio)::text = date_part('year'::text, now() - '2 years'::interval)::text
     LEFT JOIN bilanci_latest bllast ON s.id_soggetto::text = bllast.id_soggetto::text AND date_part('year'::text, bllast.data_chiusura_bilancio)::text = date_part('year'::text, now() - '3 years'::interval)::text
     LEFT JOIN ( SELECT esponenti_latest.id_soggetto,
            esponenti_latest.cd_carica,
            esponenti_latest.n_anni_esercizio,
            esponenti_latest.nascita_comune,
            esponenti_latest.nascita_dt,
            esponenti_latest.sesso,
            esponenti_latest.toponimo
           FROM esponenti_latest
         OFFSET 0
         LIMIT 1) el1 ON s.id_soggetto::text = el1.id_soggetto
     LEFT JOIN ( SELECT esponenti_latest.id_soggetto,
            esponenti_latest.cd_carica,
            esponenti_latest.n_anni_esercizio,
            esponenti_latest.nascita_comune,
            esponenti_latest.nascita_dt,
            esponenti_latest.sesso,
            esponenti_latest.toponimo
           FROM esponenti_latest
         OFFSET 1
         LIMIT 1) el2 ON s.id_soggetto::text = el2.id_soggetto
     LEFT JOIN ( SELECT esponenti_latest.id_soggetto,
            esponenti_latest.cd_carica,
            esponenti_latest.n_anni_esercizio,
            esponenti_latest.nascita_comune,
            esponenti_latest.nascita_dt,
            esponenti_latest.sesso,
            esponenti_latest.toponimo
           FROM esponenti_latest
         OFFSET 2
         LIMIT 1) el3 ON s.id_soggetto::text = el3.id_soggetto
     LEFT JOIN ( SELECT esponenti_latest.id_soggetto,
            esponenti_latest.cd_carica,
            esponenti_latest.n_anni_esercizio,
            esponenti_latest.nascita_comune,
            esponenti_latest.nascita_dt,
            esponenti_latest.sesso,
            esponenti_latest.toponimo
           FROM esponenti_latest
         OFFSET 3
         LIMIT 1) el4 ON s.id_soggetto::text = el4.id_soggetto
     LEFT JOIN provincia_regione pr ON s.provincia_cd::text = pr.codice::text
     LEFT JOIN natura_giuridica ng ON s.natura_giuridica_cd::text = ng.codice::text
     LEFT JOIN ulisse_final_info_aggiuntive ufia ON s.partita_iva::text = ufia.partita_iva::text
     LEFT JOIN settore_innolva_new ame ON s.ateco07_cd::text = ame.codice::text
     LEFT JOIN ateco_mapping am ON s.ateco07_cd::text = am.codice_purged::text
     LEFT JOIN ateco a ON s.ateco07_cd::text = a.ateco::text
     LEFT JOIN toponimi t ON s.toponimo_cd::text = t.toponimo::text
     LEFT JOIN ulisse_final uf ON s.partita_iva::text = uf.partita_iva::text
ORDER BY s.id_soggetto
